### PR TITLE
Dao

### PR DESCRIPTION
**Pull request by mtilbrook-dev**
@bizmonger I made the SQL a bit more F# ish. Let me know what you think?

### CODE REVIEW

**Comment by bizmonger** [comment]
Cannot merge at this time: https://ci.appveyor.com/project/odytrice/nikeza/build/1.0.36

**Comment by odytrice** [comment]
I think the F# style API is awesome. Clean and works well. @bizmonger What do you think? I would like to get your go-ahead so I can get rid of the commented DataAccess File?

**Comment by mtilbrook-dev** [comment]
oops left that class in there when we were refactoring yesterday. If you look at the [DataStore Diff](https://github.com/Lambda-Cartel/Nikeza/commit/020c4ad20cddfb4a35ad69525c19d56ba19bb5e5#diff-f702d84f3cea5370eb92a5aea7585e98) from yesterday we used the F# style to refactor the new database class.

**Comment by bizmonger** [comment]
You guys don't need permission to do the right thing.
Thanks.

**Comment by awright18** [comment]
I like the style! I would make a suggestion though that we put the code related to each feature or use case in the same file as opposed to all data access in one file, all routes in a file, etc.  Just a thought. Might be easier to understand/reason about and or mimic for others.

**Comment by mtilbrook-dev** [comment]
Everything for the database should be in the DataStore.

**Comment by bizmonger** [comment]
Keep code together that tends to change together.
Pull code apart that tends to change for different reasons.

**Pull request closed without merging**
