### PR TITLE
Added Authentication - issue #21

### PR DESCRIPTION
**Pull request by awright18**
I added basic registration and authentication. At the moment there are no databases involved just using the file system.  When we start deploying this somewhere we'll probably swap this out for something else, but this should allow us to continue writing code locally.  

The api urls are /register, /login, /logout.

### CODE REVIEW

**Comment by bizmonger** [comment]
Should the _register_ function return the resulting profile _Id_ to the client app?

**Comment by awright18** [comment]
I don't think so.  I don't think people should expect to be logged in after registration.  I think that you show a success message and then give them a link to the login page.

**Comment by awright18** [comment]
We might need to decide if login/registration even belongs as an elm thing or just a web page.

**Comment by bizmonger** [comment]
What's the advantage to having them perform these additional steps?

I want their data asap without them having to hop fences to do so.

**Comment by awright18** [comment]
So a trend you often see is the validation of email addresses upon registration.  I think we should be able to do something of that nature to verify the person is who they say they are upon registration.  The other option which could be an either or, is to allow registration via Google,Facebook etc, then we clearly know who they are.

It's only a one time annoyance.  It also guarantees the person knows the password they just registered with.

**Comment by bizmonger** [comment]
Thanks for clarifying.
I understand now.

**Pull request merged**
