### PR TITLE
added Bootstrap 3 framework to project. Changed index.html to reflect…

### PR DESCRIPTION
**Pull request by yelluw**
… usage of Bootstrap. Deleted old style.css file.

I've added the basics to use Bootstrap 3 as a CSS framework. This will allow to style the UI quicker.

### CODE REVIEW

**Comment by mtilbrook-dev** [comment]
Maybe try using https://github.com/rundis/elm-bootstrap instead of just pulling the bundled bootstrap CSS.

**Comment by yelluw** [comment]
Yes, I agree. Will close this and remove the PR. :)

**Comment by mtilbrook-dev** [comment]
Sure. What I would also suggest is creating a branch for each PR. I find it makes it simpler to rebase or rewrite commit history for a PR; Master is the only place I really care about true commit history.

**Comment by yelluw** [comment]
Yes, good point. Will use that workflow from now forward. 👍

**Pull request closed without merging**
